### ISSUE TITLE
6. Filtro sottostringa interna

### ISSUE THREAD

**Issue by CasarottoJoshua** [alterax05/Analizzatore-DNA#6]
Il filtro elimina tutte le sequenze che, dato un numero da 10 a 20, NON contengono più di una
ripetizione di sottostringa di dimensione data. In altre parole, considerando tutte le possibili
sottostringhe di dimensione data, non ci devono essere ripetizioni tra di loro.

**Comment by alterax05** [comment]
Come ho capito io
Prendo i primi 10<n<20 caratteri
Controllo che ci siano nella stringa
Se si, via la stinga
Se no shifto la sottostringa di 1
ripeto
es
AGGAGGGGGGAGGAGGGAGGAGGAGGGAGAAAAGAGAGAAGAGGA
n=10
AGGAGGGGGGAGGAGGGAGGAGGAGGGAGAAAAGAGAGAAGAGGA
                         AGGAGGGGGG->confronto
prossima sottostriga GGAGGGGGGA

**Comment by alterax05** [comment]
A meno che non voglia tutte le possibili combinazioni di una sottostringa di 10<n<20 caratteri
